apiVersion: v1
kind: Pod
metadata:
  name: passphrase-generator
  labels:
    app: passphrase-generator
spec:
  containers:
  - name: passphrase-generator
    image: bluesquid2/password-gen:0.0.1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: passphrase-generator-service # creates a DNS entry with this name so it can be accessed from other pods
  labels:
    app: passphrase-generator
spec:
  type: NodePort
  selector:
    app: passphrase-generator # connect to pods with this label
  ports:
    - name: http
      protocol: TCP
      port: 8080 # port to access the service from within the cluster
      targetPort: 8080
      nodePort: 30000 # port to access the service from outside the cluster