---
- name: Website deployment
  become: yes
  hosts: new_vps
  vars:
    ansible_user: root

  tasks:
    - name: Copy latest project config files
      copy:
        src: ../../config/
        dest: /home/web/config/
        owner: web
        group: web
        mode: 'preserve'

    - name: Create symlink for systemd service
      file:
        src: /home/web/config/systemd
        dest: /usr/local/lib/systemd/system
        state: link

- name: Website deployment
  become: yes
  hosts: current_vps
  vars:
    ansible_user: root
  tasks:
    - name: Archive config files from current VPS
      archive:
        path: /home/web/config/
        dest: /tmp/web_config.tar.gz
        mode: 'u+rw'
        format: gz
        force_archive: true

    - name: Grab latest config from current VPS
      fetch:
        flat: yes
        src: /tmp/web_config.tar.gz
        dest: /tmp/

- name: Website deployment
  become: yes
  hosts: new_vps
  vars:
    ansible_user: root
  tasks:
    - name: Extract config files on new VPS
      unarchive:
        src: /tmp/web_config.tar.gz
        dest: /home/web/config/
        owner: web
        group: web
        
    - name: Reload systemd services
      systemd:
        daemon-reload: yes

    - name: Start web docker container
      systemd:
        name: ism-web
        state: restarted
        enabled: yes

    - name: Enable certbot timer
      systemd:
        name: certbot.timer
        state: started
        enabled: yes