- name: Copy kubernetes deployment file
  copy:
    src: ../../deployment.yaml
    dest: /home/k8s/deployment.yaml
    owner: k8s
    group: k8s
    mode: '0644'

- name: Apply kubernetes deployment
  become: yes
  become_user: k8s
  shell: kubectl apply -f /home/k8s/deployment.yaml

- name: Wait for the pod to be ready
  become: yes
  become_user: k8s
  shell: |
    kubectl wait --for=condition=Ready pod/passphrase-generator --timeout=60s
  register: wait_result
  failed_when: "'condition met' not in wait_result.stdout"
  changed_when: false

- name: create ngnix config folder
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0644'

- name: copy nginx config
  copy:
    src: config/default.conf
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'

- name: copy docker compose file
  copy:
    src: config/compose.yaml
    dest: /home/ngnix/compose.yaml
    owner: ngnix
    group: ngnix
    mode: '0644'

- name: Run docker-compose
  become: yes
  become_user: ngnix
  community.docker.docker_compose_v2:
    project_src: /home/ngnix