- name: Copy kubernetes deployment file
  copy:
    src: ../../deployment.yaml
    dest: /home/k8s/deployment.yaml
    owner: k8s
    group: k8s
    mode: '0644'

- name: Apply kubernetes deployment
  become: yes
  become_user: k8s
  shell: kubectl apply -f /home/k8s/deployment.yaml

- name: Wait for the pod to be ready
  become: yes
  become_user: k8s
  shell: |
    kubectl wait --for=condition=Ready pod/passphrase-generator --timeout=60s
  register: wait_result
  failed_when: "'condition met' not in wait_result.stdout"
  changed_when: false