- name: Copy latest project config files
  copy:
    src: ../../config/
    dest: /home/web/config/
    owner: web
    group: web
    mode: 'preserve'

- name: Create symlink for systemd service
  file:
    src: /home/web/config/systemd
    dest: /usr/local/lib/systemd/system
    state: link

# Copy state from previous instance

- name: reload systemd services
  systemd:
    daemon-reload: yes

- name: Start web docker container
  systemd:
    name: ism-web
    state: restarted
    enabled: yes

- name: Enable certbot timer
  systemd:
    name: certbot.timer
    state: started
    enabled: yes