- name: vps-setup
  become: yes
  hosts: all
  vars:
    ansible_user: root
  tasks:
    - name: Install Docker
      import_tasks: install-docker.yml

    - name: Deploy website
      import_tasks: deploy-website.yml

    - name: OS hardening
      import_tasks: os-hardening.yml