- name: vps-setup
  become: yes
  hosts: all
  vars:
    ansible_user: root
  tasks:
    - name: Install kubernetes
      import_tasks: kubernetes.yml

    - name: Deploy website
      import_tasks: deploy-website.yml

    - name: os hardening
      import_tasks: os-hardening.yml