- name: vps-setup
  become: yes
  hosts: all
  vars:
    ansible_user: root
  tasks:
    - name: Configure host
      import_tasks: os-config.yml

    - name: Install kubernetes
      import_tasks: kubernetes.yml