- name: Install docker-ce and docker-compose
  apt:
    name:
      - docker-ce
      - docker-compose

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create ngnix user
  user:
    name: ngnix
    shell: /bin/bash
    groups: docker
    home: /home/ngnix

- name: Delete existing ngnix configs files
  file:
    path: /home/ngnix/config
    state: absent

- name: Bulk sync ngnix config files
  copy:
    src: config/
    dest: /home/ngnix/config/

- name: Create local systemd service folder
  file:
    path: /usr/local/lib/systemd
    state: directory

- name: Create symlink for systemd service
  file:
    src: /home/ngnix/config/systemd
    dest: /usr/local/lib/systemd/system
    state: link

# certbot needs the http server to be running to verify domain ownership
# Ngnix crashes if the https server is not configured properly so remove it
# until the cert is generated.
- name: Remove https config
  file:
    path: /home/ngnix/config/conf.d/ngnix-https.conf
    state: absent

- name: Start ngnix docker container
  systemd:
    name: ngnix
    state: restarted
    daemon-reload: yes

# Certbot has rate limiting. To prevent hitting the rate limit,
# we need to check if the cert already exists
- name: Check if cert already exists
  stat:
    path: /home/ngnix/ssl/www.pagepress.com.au/fullchain.pem
  register: cert_stat

- name: Generate ssl cert
  when: not cert_stat.stat.exists
  systemd:
    name: certbot.service
    state: restarted

- name: Add https only nginx config
  copy:
    src: config/conf.d/ngnix-https.conf
    dest: /home/ngnix/config/conf.d/https-only.conf

- name: Restart ngnix docker container and enable it
  systemd:
    name: ngnix
    state: restarted
    enabled: yes

- name: Enable certbot timer
  systemd:
    name: certbot.timer
    state: started
    enabled: yes