- name: Create .ssh folder in k8s home
  become: yes
  become_user: k8s
  file:
    path: ~/.ssh
    state: directory

- name: Copy ssh key from root to k8s
  copy:
    src: /root/.ssh/authorized_keys
    dest: /home/k8s/.ssh/authorized_keys
    remote_src: yes

- name: Install UFW
  apt:
    name: ufw

- name: Allow SSH through UFW
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow HTTP through UFW
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS through UFW
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled

# - name: remove ssh key from root user
#   file:
#     path: /root/.ssh/authorized_keys
#     state: absent

# - name: disable root user from SSH
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     regexp: '^#?PermitRootLogin'
#     line: 'PermitRootLogin no'
#     state: present
#     backup: yes