services:
  ngnix:
    image: "nginx:1.28.0-alpine"
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /home/ngnix/conf.d/:/etc/nginx/conf.d/:ro # nginx config
      - /home/ngnix/www/.well-known/acme-challenge/:/var/www/.well-known/acme-challenge/:ro # used to verify domain ownership
      - /home/ngnix/ssl/:/etc/ssl/:ro # certificate key output folder
    extra_hosts:
      - "host.docker.internal:host-gateway"