services:
  ngnix:
    image: "nginx:1.28.0-alpine"
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro # nginx config
      # - /var/www/certbot/:/var/www/certbot/:ro # used to verify domain ownership
      # - /etc/letsencrypt/:/etc/ssl/:ro # certificate key output folder
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # certbot:
  #   image: "certbot/certbot:v4.0.0"
  #   volumes:
  #     # - /var/lib/letsencrypt:/var/lib/letsencrypt
  #     - /var/www/certbot/:/var/www/certbot/:rw # used to verify domain ownership
  #     - /etc/ssl/:/etc/letsencrypt/:rw # certificate key output folder
  #   command: certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d pagepress.com.au