services:
  ngnix:
    image: "nginx:1.28.0-alpine"
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    